/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.src.test.java.adventofcode;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    
}
